[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "uvicorn dashboard_api:app --host 0.0.0.0 --port $PORT"
sleepApplication = true
restartPolicyType = "NEVER"

# Environment variables for the cron job
[deploy.env]
PYTHONPATH = "/app:/app/daily_run"
PYTHONUNBUFFERED = "1"
TZ = "America/New_York"

# Primary cron job - 10:05 PM UTC (5:05 PM ET after market close)
[[cron]]
schedule = "5 22 * * *"
command = "python run_daily_cron_test.py"

# Backup cron job - 11:05 PM UTC (6:05 PM ET) in case primary fails
[[cron]]
schedule = "5 23 * * *"
command = "python run_daily_cron_test.py" 