[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
runtime = "V2"
numReplicas = 1
cronSchedule = "5 22 * * MON-FRI"
startCommand = "python daily_run.py"
sleepApplication = false
restartPolicyType = "NEVER"