[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "echo 'No persistent service, uses cron only.'"

[cron]
schedule = "5 22 * * MON-FRI"
command = "python daily_run/daily_run.py"