[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd /app && python /app/railway_cron_entry.py"
sleepApplication = true
restartPolicyType = "NEVER"
cronSchedule = "5 22 * * *"

# Environment variables for the cron job
[deploy.env]
PYTHONPATH = "/app:/app/daily_run:/app/utility_functions"
PYTHONUNBUFFERED = "1"
TZ = "America/New_York"
WORKDIR = "/app"

# Primary cron job using Railway's built-in cron
[[cron]]
schedule = "5 22 * * *"
command = "python railway_cron_entry.py" 